# Site settings
title: Multi-cloud File System
email: mcfsadm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  McFS project is still under active development. If you are
  interested in participating in this open source project, email
  us at mcfsadm@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mcfs.github.io" # the base hostname & protocol for your site
#twitter_username: 
github_username:  mcfs

# Build settings
markdown: kramdown
